version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: emulatorjs_web_1
      APP_PORT: 80

  web:
    image: lscr.io/linuxserver/emulatorjs:latest
    restart: on-failure
    ports:
      - 3456:3000
    environment:
      - PUID=1000
      - PGID=1000
      - SUBFOLDER=/ #optional
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/data
